import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // CATÁLOG
//CADASTRO
containerCadastro: {
  flex: 1,
  width: '100%',
  height: '100%',
},
containerviewCadastro: {
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
},
closeIconCadastro: {
  position: 'absolute',
  top: "1%",
  right: "5%",
},
backgroundCadastro: {
  flex: 1,
  width: '100%',
  height: '100%',
  alignItems: 'center',
  justifyContent: 'center',
},
avatarCadastro: {
  width: 100,
  height: 100,
  borderRadius: 50,
  alignSelf: 'center',
  marginBottom: 40,
  borderWidth: 1,
  borderColor: 'white',
  blurRadius: 100,
},
inputContainerCadastro: {
  flexDirection: 'row',
  alignItems: 'center',
  borderBottomColor: 'white',
  marginBottom: 15,
},
InputNameCadastro: {
  width: 290,
  height: 40,
  color: 'white',
  paddingHorizontal: 5,
  borderWidth: 0.5,
  borderColor: 'white',
  borderRadius: 5,
},
InputMailCadastro: {
  width: 290,
  height: 40,
  color: 'white',
  paddingHorizontal: 5,
  borderWidth: 0.5,
  borderColor: 'white',
  borderRadius: 5,
},
BtnCadastroCadastro: {
  alignSelf: "center",
  alignItems: "center",
  justifyContent: "center",
  height: 40,
  width: 150,
  marginTop: 15,
  borderRadius: 8,
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
},
cdsButtonTextCadastro: {
  color: 'white',
  fontSize: 15,
  fontWeight: 'bold',
},
viewCdsCadastro: {
  height: '68%',
  width: '80%',
  backgroundColor: 'rgba(255, 255, 255, 0.2)',
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: 0.5,
  borderColor: 'white',
  borderRadius: 45,
  overflow: 'hidden',
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
},
titleTextCadastro: {
  color: 'white',
  fontSize: 24,
  fontWeight: 'bold',
  alignSelf: 'flex-start',
  marginLeft: 20,
  marginBottom: 30,
},

//LOGIN
containerLogin: {
  flex: 1,
  display: 'flex',
  backgroundColor: 'white',
  padding: 0,
  margin: 0,
  alignItems: 'center',
  justifyContent: 'center',
},
closeIconLogin: {
  position: 'absolute',
  top: "1%",
  right: "5%",
},
backgroundLogin: {
  flex: 1,
  width: '100%',
  height: '100%',
  alignItems: 'center',
  justifyContent: 'center',
},
inputContainerLogin: {
  flexDirection: 'row',
  alignItems: 'center',
  borderBottomColor: 'white',
  marginBottom: 15,
},
InputNameLogin: {
  width: 290,
  height: 40,
  color: 'white',
  paddingHorizontal: 5,
  borderWidth: 0.5,
  borderColor: 'white',
  borderRadius: 5,
},
BtnLogin: {
  alignSelf: "center",
  alignItems: "center",
  justifyContent: "center",
  height: 45,
  width: 300,
  marginTop: 20,
  borderRadius: 8,
  shadowColor: "#000",
  shadowOffset: {
    width: 0,
    height: 2,
  },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
},
cdsButtonTextLogin: {
  color: 'white',
  fontSize: 15,
  fontWeight: 'bold',
},
viewCdsLogin: {
  height: '68%',
  width: '80%',
  backgroundColor: 'rgba(255, 255, 255, 0.1)',
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: 0.5,
  borderColor: 'white',
  borderRadius: 45,
  overflow: 'hidden',
  shadowColor: "#000",
  shadowOffset: {
    width: 0,
    height: 4,
  },
  shadowOpacity: 0.3,
  shadowRadius: 5,
  elevation: 8,
},
titleTextLogin: {
  color: 'white',
  fontSize: 24,
  fontWeight: 'bold',
  alignSelf: 'flex-start',
  marginLeft: 20,
  marginTop: 20,
},
subtitleTextLogin: {
  color: 'white',
  fontSize: 14,
  alignSelf: 'flex-start',
  marginLeft: 20,
  marginBottom: 20,
},
forgetPasswordTextLogin: {
  color: 'white',
  marginTop: 10,
  textDecorationLine: 'underline',
  alignSelf: 'center',
},
signUpTextLogin: {
  color: 'white',
  alignSelf: 'center',
  marginTop: '100%',
  position: 'absolute',
  textDecorationLine: 'underline',
},  
});